'use strict';
module.exports = Object.freeze({ CREATED:'CREATED', INITIALIZING:'INITIALIZING', INITIALIZED:'INITIALIZED', STARTING:'STARTING', RUNNING:'RUNNING', STOPPING:'STOPPING', STOPPED:'STOPPED', FAILED:'FAILED' });
