'use strict';
const test=require('node:test'); const assert=require('node:assert/strict');
const B1StorageProtectionPlanner=require('../../../src/planning/storage/B1StorageProtectionPlanner');
function policy(){return {resources:{iron:{baseId:'iron',blockId:'iron_block',sellId:'iron_block',ratio:9}},coverageSnapshot(snapshot){const blocks=Number(snapshot.items.iron_block||0); const loose=Number(snapshot.items.iron||0); const effectiveB1=loose+blocks*9; return {iron:{baseId:'iron',requiredPerB5:64,effectiveB1,coverage:effectiveB1/64}};}};}
function compile(items,reserveCoverage=1.5){return new B1StorageProtectionPlanner({materialPolicy:policy()}).compile({snapshot:{items},reserveCoverage,freshness:{confirmed:true,expectedGeneration:3,currentGeneration:3},profile:{id:'fake',revision:'p1'},policy:{id:'b5-storage',revision:'v1'}});}
test('WP-302 planner keeps exact reserve floor and sells only complete 64-item block slices',()=>{const p=compile({iron_block:100}); assert.equal(p.decision.kind,'SELL_SURPLUS_64'); assert.ok(p.actions.length>0); assert.ok(p.actions.every(a=>a.quantity===64)); const sold=p.actions.length*64; assert.ok((100-sold)*9>=96); assert.ok((100-(sold+64))*9<96);});
test('WP-302 equality at reserve boundary is NOOP',()=>{const p=compile({iron_block:11}); assert.equal(p.actions.length,0); assert.equal(p.decision.kind,'NOOP');});
test('WP-302 baseline below the hard reserve is a non-selling readiness condition, not a planner blocker',()=>{const p=compile({iron_block:10}); assert.equal(p.decision.kind,'NOOP'); assert.equal(p.actions.length,0); assert.equal(p.blockers.length,0); assert.ok(p.reserveShortages.some(b=>b.code==='RESERVE_INPUT_PENDING'&&b.baseId==='iron'&&b.coverage<1.5));});
test('WP-302 incomplete, unconfirmed and stale snapshots fail closed',()=>{const planner=new B1StorageProtectionPlanner({materialPolicy:policy()}); assert.equal(planner.compile({snapshot:null,freshness:{confirmed:true}}).decision.kind,'BLOCKED'); assert.equal(planner.compile({snapshot:{items:{}},freshness:{confirmed:false}}).decision.kind,'BLOCKED'); assert.ok(planner.compile({snapshot:{items:{}},freshness:{confirmed:true,expectedGeneration:1,currentGeneration:2}}).blockers.some(b=>b.code==='STALE_GENERATION'));});
test('WP-302 plan is immutable/deterministic and later inflow cannot expand an existing plan',()=>{const one=compile({iron_block:100}); const copy=JSON.stringify(one.actions); const later=compile({iron_block:1000}); assert.equal(JSON.stringify(one.actions),copy); assert.ok(later.actions.length>one.actions.length); assert.equal(Object.isFrozen(one),true); assert.equal(one.replayEnvelope.domain,'storage-protection');});
test('WP-302 block-only contract never plans a base or raw resource sale',()=>{const materialPolicy={resources:{stone:{baseId:'stone',blockId:null,sellId:'stone',ratio:1}},coverageSnapshot(snapshot){const effectiveB1=Number(snapshot.items.stone||0); return {stone:{baseId:'stone',requiredPerB5:16,effectiveB1,coverage:effectiveB1/16}};}}; const planned=new B1StorageProtectionPlanner({materialPolicy}).compile({snapshot:{items:{stone:10000}},reserveCoverage:1.5,freshness:{confirmed:true}}); assert.equal(planned.actions.length,0); assert.equal(planned.totalSellItems,0); assert.equal(planned.decision.kind,'NOOP');});
